spring:
  application:
    name: "HR Easy Telegram Bot"
  thymeleaf:
    prefix: classpath:/responses/
    suffix: .md
    cache: false
    mode: TEXT

hreasy:
  telegram:
    bot-username: "not_defined"
    bot-token: "not_defined"
    bot-creator: 1

logging:
  level:
    ru.abondin: DEBUG
