# Use root/example as user/password credentials
version: '3.7'

services:
  hreasydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: HREasyPassword2019!
      ACCEPT_EULA: Y
      MSSQL_COLLATION: Cyrillic_General_100_CI_AS
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - ./dbbackup:/var/backups
      - hreasydata:/var/opt/mssql
    container_name: hreasydb
  hreasyplatform:
    image: docker.k8s-usn.stm.local:80/hreasyplatform:latest
    restart: unless-stopped
    environment:
      SERVER_PORT: 80
      HREASY_DB_HOST: hreasydb
      HREASY_DB_USERNAME: sa
      HREASY_DB_PASSWORD: HREasyPassword2019!
      HREASY_DB_DATABASE: hr
      HREASY_LDAP_SERVER-URL: ldap://dc.stm.local
      HREASY_LDAP_USER-DN: CN=ldapquery,CN=Users,DC=stm,DC=local
      HREASY_LDAP_USER-PASSWORD:
    depends_on:
      - hreasydb
    ports:
      - 80
    container_name: hreasyplatform
  hreasyweb:
    image: docker.k8s-usn.stm.local:80/hreasyweb:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - hreasyplatform
    container_name: hreasyweb
volumes:
  hreasydata: