# Use root/example as user/password credentials
version: '3.1'

services:
  hreasypg:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: HREasyPassword2019!
      POSTGRES_DB: hr
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: hreasypg
  hreasyplatform:
    image: docker.io/abondin/hreasyplatform:latest
    restart: unless-stopped
    volumes:
      - ./store:/opt/hreasy/store
    environment:
      SERVER_PORT: 80
      HREASY_FS_RESOURCE_PATH: file:/opt/hreasy/store
      HREASY_DB_HOST: hreasypg
      HREASY_DB_PORT: 5432
      HREASY_DB_USERNAME: hr
      HREASY_DB_PASSWORD: HREasyPassword2019!
      HREASY_DB_DATABASE: hr
      HREASY_WEB_SEC_MASTER-PASSWORD: qwe123
      HREASY_BACKGROUND_UPCOMING-VACATION_JOB-ENABLED: 'false'
      HREASY_COMMON_DEFAULT-EMAIL-FROM: hreasy@company.org
      HREASY_COMMON_WEB-BASE-URL: http://localhost:8080
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      JAVA_TOOL_OPTIONS: -Duser.country=RU -Duser.language=ru -Duser.timezone=Europe/Moscow
    depends_on:
      - hreasypg
    ports:
      - 80
    container_name: hreasyplatform
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
  hreasyweb:
    image: docker.io/abondin/hreasyweb:latest
    restart: unless-stopped
    depends_on:
      - hreasyplatform
    ports:
      - 8080:80
    container_name: hreasyweb
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
  hreasytg:
    image: docker.io/abondin/hreasytelegram:latest
    restart: unless-stopped
    depends_on:
      - hreasyplatform
    container_name: hreasytg
    environment:
      HREASY_TELEGRAM_BOT_USERNAME: <MY_SUPER_BOT>
      HREASY_TELEGRAM_BOT_TOKEN: <BOT TOKEN>
      HREASY_TELEGRAM_BOT_CREATOR: <MY TELEGRAM USER ID>
      HREASY_TELEGRAM_PLATFORM_BASE-URL: 'http://localhost:8081/telegram/'
      HREASY_TELEGRAM_PLATFORM_WEB-INTERFACE-URL: 'https://localhost:8080'
      JAVA_TOOL_OPTIONS: -Duser.country=RU -Duser.language=ru -Duser.timezone=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
volumes:
  hreasydata: