# Use root/example as user/password credentials
version: '3.7'

services:
  hreasypg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: HREasyPassword2019!
      POSTGRES_DB: hr
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: hreasypg

  hreasyplatform:
    image: docker.k8s-usn.stm.local:80/hreasyplatform:latest
    restart: "no" #unless-stopped
    volumes:
      - ./store:/opt/hreasy/store
    environment:
      SERVER_PORT: 80
      HREASY_FS_RESOURCE_PATH: file:/opt/hreasy/store
      HREASY_DB_HOST: hreasydb
      HREASY_DB_USERNAME: sa
      HREASY_DB_PASSWORD: HREasyPassword2019!
      HREASY_DB_DATABASE: hr
      HREASY_LDAP_SERVER-URL: ldap://dc.stm.local
      HREASY_LDAP_USER-DN: CN=ldapquery,CN=Users,DC=stm,DC=local
      HREASY_LDAP_USER-PASSWORD:
    depends_on:
      - hreasydb
    ports:
      - 80:80
    container_name: hreasyplatform
  hreasyweb:
    image: docker.k8s-usn.stm.local:80/hreasyweb:latest
    restart: "no" #unless-stopped
    ports:
      - 80:80
    depends_on:
      - hreasyplatform
    container_name: hreasyweb
volumes:
  hreasydata: