hreasy:
  # Hack to support both Flyway JDBC and Spring R2DBC urls to the database
  db:
    #host: sql.hr
    host: localhost
    port: 5432
    database: hr
    username: hr
    password: HREasyPassword2019!
  web:
    sec:
      cors-allowed-origins: http://localhost:8080
      master-password: qwe123
      internal-password-enabled: true
  ldap:
    #server-url: "ldap://192.168.10.11"
    #user-dn: "CN=ldapquery,CN=Users,DC=stm,DC=local"
    #user-password: "NOT SET"
    #search-base: "OU=Internal,OU=Enterprise,DC=stm,DC=local"

logging:
  level:
    org:
      springframework:
        data: INFO
    ru:
      abondin: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

spring:
  mail:
    host: smtp.yandex.ru
    username:
    password:
    port: 465
    protocol: smtps