hreasy:
  # Hack to support both Flyway JDBC and Spring R2DBC urls to the database
  db:
    host: sql.hr
    port: 5432
    database: hr
    username: hr
    password: HREasyPassword2019!
  web:
    sec:
      cors-allowed-origins: http://localhost:8080
      master-password: qwe123

logging:
  level:
    org:
      springframework:
        data: INFO
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
