hreasy:
  # Hack to support both Flyway JDBC and Spring R2DBC urls to the database
  db:
    host: sql.hr
    port: 1433
    database: master
    username: sa
    password: HREasyPassword2019!
  web:
    sec:
      cors-allowed-origins: http://localhost:8080
      master-password: qwe123

logging:
  level:
    org:
      springframework:
        data: INFO
