CREATE SCHEMA IF NOT EXISTS notify;

CREATE SEQUENCE IF NOT EXISTS notify.NOTIFICATION_ID_SEQ;
CREATE TABLE IF NOT EXISTS notify.notification (
	id integer PRIMARY KEY NOT NULL DEFAULT nextval('notify.NOTIFICATION_ID_SEQ'),
	employee integer NOT NULL REFERENCES empl.employee (id),
	client_uuid varchar(36) NOT NULL,
	category varchar(255) NOT NULL,
	title varchar(1024) NOT NULL,
	markdown_text text NOT NULL,
	context jsonb NULL,
	created_at timestamp with time zone NOT NULL,
    created_by integer NULL REFERENCES empl.employee (id),
	acknowledged_at timestamp with time zone NULL,
    acknowledged_by integer NULL REFERENCES empl.employee (id),
	archived_at timestamp with time zone NULL,
    archived_by integer NULL REFERENCES empl.employee (id)
);
ALTER TABLE notify.notification ADD CONSTRAINT notification_client_uuid_uk UNIQUE ("employee","client_uuid");

COMMENT ON TABLE notify.notification IS 'Employee notification';
COMMENT ON COLUMN notify.notification.id IS 'Primary key to link with other tables';
COMMENT ON COLUMN notify.notification.employee IS 'Link to employee';
COMMENT ON COLUMN notify.notification.client_uuid IS 'Generated by client notification UUID. Unique for employee';
COMMENT ON COLUMN notify.notification.category IS 'Notification category';
COMMENT ON COLUMN notify.notification.title IS 'Link to employee';
COMMENT ON COLUMN notify.notification.markdown_text IS 'Text to show in markdown format';
COMMENT ON COLUMN notify.notification.context IS 'JSON with key-value (like {employeeId:1}) context to help UI functionality (like navigate to some page)';
COMMENT ON COLUMN notify.notification.created_at IS 'Created at';
COMMENT ON COLUMN notify.notification.created_by IS 'Created by (link to employee). Null if created automatically by system';
COMMENT ON COLUMN notify.notification.acknowledged_at IS 'Acknowledged at';
COMMENT ON COLUMN notify.notification.acknowledged_by IS 'Acknowledged by (link to employee)';
COMMENT ON COLUMN notify.notification.archived_at IS 'Archived at';
COMMENT ON COLUMN notify.notification.archived_by IS 'Archived by (link to employee)';

-- Additional permission to create new notification from admin UI
INSERT INTO sec.perm (permission,description) VALUES
	 ('admin_notifications','Create notifications for the employees');
INSERT INTO sec.role_perm (role,permission) VALUES
	 ('global_admin','admin_notifications'),
	 ('hr','admin_notifications'),
	 ('content_management','admin_notifications');
