ALTER TABLE sec.role_perm ADD CONSTRAINT role_perm_uk UNIQUE ("role","permission");

INSERT INTO sec."role" ("role",description) VALUES
	 ('content_management','Create/update and moderate articles and news'),
	 ('finance','Work with business account positions and expenses'),
	 ('global_admin','Full access'),
	 ('hr','Add/Update/Fire all employees'),
	 ('pm','Project Manager') on conflict do nothing;

INSERT INTO sec.role_perm ("role","permission") VALUES
	 ('global_admin','update_current_project_global'),
	 ('global_admin','update_avatar'),
	 ('hr','update_current_project_global'),
	 ('hr','update_avatar'),
	 ('global_admin','overtime_view'),
	 ('global_admin','overtime_edit'),
	 ('hr','overtime_view'),
	 ('hr','overtime_edit'),
	 ('global_admin','vacation_view'),
	 ('global_admin','vacation_edit'),
	 ('hr','vacation_view'),
	 ('hr','vacation_edit'),
	 ('pm','overtime_view'),
	 ('pm','overtime_edit'),
	 ('pm','vacation_view'),
	 ('pm','vacation_edit'),
	 ('pm','update_current_project'),
	 ('global_admin','overtime_admin'),
	 ('global_admin','update_project'),
	 ('global_admin','create_project'),
	 ('pm','create_project'),
	 ('global_admin','project_admin_area'),
	 ('pm','project_admin_area'),
	 ('global_admin','admin_users'),
	 ('global_admin','edit_skills'),
	 ('pm','edit_skills'),
	 ('hr','edit_skills'),
	 ('global_admin','edit_business_account'),
	 ('global_admin','assign_to_ba_position'),
	 ('pm','assign_to_ba_position'),
	 ('finance','edit_business_account'),
	 ('global_admin','edit_articles'),
	 ('content_management','edit_articles'),
	 ('global_admin','view_employee_full'),
	 ('global_admin','edit_employee_full'),
	 ('hr','view_employee_full'),
	 ('hr','edit_employee_full'),
	 ('global_admin','view_assessment_full'),
	 ('global_admin','create_assessment'),
	 ('hr','view_assessment_full'),
	 ('hr','create_assessment'),
	 ('pm','create_assessment') on conflict do nothing;

