@startuml
'https://plantuml.com/ru/activity-diagram-beta
start


partition "Available flows" {
    fork
        :Start instructions;
    fork again
        :Update Password;
    fork again
        :generate JWT token with user telegram account;
        :REST API method with "Authorization Bearer" header;
        fork
           : /my-info Information about me;
        fork again
           :/vacations Check vacations;
        end fork
        if (HTTP Result) then (200 OK)
            : Print the information;
        else
            :401 User not found by given telegram account
            422 Business Error
            403 Forbidden;
            stop
        end if
    end fork
}



stop
@enduml