# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-platform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
   
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Build with Maven
    - name: Build Platform
      run: mvn -B package --file platform/pom.xml

    - name: Build Telegram Bot
      run: mvn -B package --file telegram/pom.xml

    # Generate Platform unit test report
    - name: Publish Test Report
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'

    # Build Docker
    - name: Build and push docker platform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        GITHUB_NAME: ${{ secrets.GITHUBNAME }}
      run: mvn -B jib:build -Dimage='docker.io/abondin/hreasyplatform' -Djib.to.auth.username=${GITHUB_NAME} -Djib.to.auth.password=${GITHUB_TOKEN} --file platform/pom.xml

    - name: Build and push docker telegram bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        GITHUB_NAME: ${{ secrets.GITHUBNAME }}
      run: mvn -B jib:build -Dimage='docker.io/abondin/hreasytelegram' -Djib.to.auth.username=${GITHUB_NAME} -Djib.to.auth.password=${GITHUB_TOKEN} --file telegram/pom.xml

   
  build-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/abondin/hreasyweb
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GITHUBNAME }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context:  web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

